# This file was generated by GoReleaser. DO NOT EDIT.
cask "whosthere" do
  version "0.8.3"

  on_macos do
    on_intel do
      sha256 "e79ee001d276c3842c17d48699e730b037e450c2bd2327e09a2f5798251d3f4e"
      url "https://github.com/ramonvermeulen/whosthere/releases/download/v#{version}/whosthere_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "51ee6ce87931a4f8707c0d1fbce9c0813af908370f2620182880d9df431e09d3"
      url "https://github.com/ramonvermeulen/whosthere/releases/download/v#{version}/whosthere_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "73e2f9b4887d6abe3334f6da61e1b8c701da89198e99a03b7a20c5c5473d68ca"
      url "https://github.com/ramonvermeulen/whosthere/releases/download/v#{version}/whosthere_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bada504d3ae8ac255d20dbe580e4d7051db3a60855ee367d45bb2437ab87b85f"
      url "https://github.com/ramonvermeulen/whosthere/releases/download/v#{version}/whosthere_#{version}_linux_arm64.tar.gz"
    end
  end

  name "whosthere"
  desc "Local network discovery tool with an interactive Terminal User Interface (TUI) written in Go."
  homepage "https://github.com/ramonvermeulen/whosthere"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whosthere"

  # No zap stanza required

end
